config/routes.rb
Rails.application.routes.draw do
  devise_for :users, sign_out_via: [:get]
    resources :users
    resources :foods
    resources :recipes do
    resources :recipe_foods, only: %i[new create destroy]
  end
  root 'foods#index'
  get '/general_shopping_list', to: 'foods#general'
  get '/public_recipes', to: 'recipes#public'
end

app/models/recipe.rb
class Recipe < ApplicationRecord
  belongs_to :user
  has_many :recipe_foods
  has_many :foods, through: :recipe_foods

  validates :name, presence: true, length: { maximum: 250 }
  validates :description, presence: true
end

app/controllers/recipes_controller.rb
class RecipesController < ApplicationController
  load_and_authorize_resource
  before_action :set_recipe, only: %i[show edit destroy]

  # GET /recipes or /recipes.json
  def index
    @recipes = Recipe.all
  end

  # GET /recipes/1 or /recipes/1.json
  def show; end

  # GET /recipes/new
  def new
    @recipe = Recipe.new
  end

  def public
    @totals = {}
    @public_recipes = Recipe.where(public: true).order('created_at DESC')
    @public_recipes.each do |p|
      total = 0
      RecipeFood.where(recipe_id: p.id).each do |rf|
        total += rf.quantity * rf.food.price
      end
      @totals[p.name] = total
    end
  end

  # POST /recipes or /recipes.json
  def create
    @recipe = Recipe.new(recipe_params)
    @recipe.user = current_user

    respond_to do |format|
      if @recipe.save
        format.html { redirect_to recipe_url(@recipe), notice: 'Recipe was successfully created.' }
        format.json { render :show, status: :created, location: @recipe }
      else
        format.html { render :new, status: :unprocessable_entity, notice: 'Recipe not added' }
        format.json { render json: @recipe.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /recipes/1 or /recipes/1.json
  def destroy
    respond_to do |format|
      @recipe.recipe_foods.destroy_all
      if @recipe.destroy
        format.html { redirect_to recipes_url, notice: 'Recipe was successfully deleted.' }
        format.json { head :no_content }
      else
        format.html { render :new, status: :unprocessable_entity, notice: 'Recipe not deleted' }
        format.json { render json: @recipe.errors, status: :unprocessable_entity }
      end
    end
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_recipe
    @recipe = Recipe.find(params[:id])
  end

  # Only allow a list of trusted parameters through.
  def recipe_params
    params.require(:recipe).permit(:name, :description, :cooking_time, :public, :preparation_time)
  end
end

app/views/recipes/_form.html.erb
<%= form_with(model: recipe) do |form| %>
  <% if recipe.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(recipe.errors.count, "error") %> prohibited this recipe from being saved:</h2>

      <ul>
        <% recipe.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/recipes/_recipe.html.erb
<div class='rectangle' id="<%= dom_id recipe %>">
    <h2> <%= link_to recipe.name, recipe %></h2>
     <% if can? :delete, recipe %>
   <div class="btn-destroy">
        <%= button_to "Delete", recipe_path(id: recipe.id), method: :delete %>
    </div>
    <% end %>
    <p class='shownot'><%= recipe.preparation_time %></p>
    <p class='shownot'><%= recipe.cooking_time %></p>
    <p class='info-desc'><%= recipe.description %></p>
</div>

app/views/recipes/edit.html.erb
<h1 class="recipe-header">Editing recipe</h1>

<%= render "form", recipe: @recipe %>

<br>

<div class="links">
  <%= link_to "Show this recipe", @recipe %> |
  <%= link_to "Back to recipes", recipes_path %>
</div>

app/views/recipes/index.html.erb
<h1 class="recipe-header">Recipes</h1>

<div id="recipes">
  <% @recipes.each do |recipe| %>
    <%= render recipe %>
  <% end %>
</div>
<div class="new-recipe">
<%= link_to "New recipe", new_recipe_path %>
</div>

app/views/recipes/new.html.erb
<h1 class="recipe-header">New recipe</h1>

<%= form_with model: @recipe, url: recipes_path, method: :post, local: true, scope: :recipe, class: "form" do |form| %>
  <div class='form-text-wrapper' >
    <div class="form-texts">
     <%= form.label :name %>
     <%= form.text_field :name %>
    </div>
    <div class="form-texts">
     <%= form.label :description %>
     <%= form.text_area :description %>
    </div>
    <div class="form-texts">
      <%= form.label :preparation_time %>
      <%= form.text_field :preparation_time %>
    </div>
    <div class="form-texts">
      <%= form.label :cooking_time %>
      <%= form.text_field :cooking_time %>
    </div>
    <div>
      <%= form.radio_button :public,  true %>
      <%= form.label :public, "Public recipe" %>
    </div>
    <div>
      <%= form.radio_button :public, false %>
      <%= form.label :public, "Not public recipe" %>
    </div>
  </div>
  <%= form.submit %>
<% end %>
<br>
<div class="new-recipe">
  <%= link_to "Back to recipes", recipes_path %>
</div>

app/views/recipes/public.html.erb
<div class="form-wrapper">
    <h3 class="recipe-header">Public Recipes</h3>
    <ul class="state">
      <% @public_recipes.each do |recipe| %>
        <li class="pub">
          <div class="pub-link">
            <div>
              <%= link_to recipe.name, recipe_path(recipe) %>
            </div>
            <span>By: <%= recipe.user.name %></span>
          </div>
          <div class="pub-link">
            <div>
              <span>Total food items: </span>
              <span><%= recipe.foods.length %></span>
            </div>
            <div class="pub-link">
              <span>Total price:</span>
              <% if recipe.recipe_foods.find_by(recipe_id: recipe.id) %>
                    <span><%= recipe.recipe_foods.find_by(recipe_id: recipe.id).quantity * recipe.recipe_foods.find_by(recipe_id: recipe.id).food.price %></span>
              <% else %>
                <span>0</span>
              <% end %>
            </div>
          </div>
        </li>
      <% end %>
    </ul>
  </div>

app/views/recipes/show.html.erb
<h2 class="recipe-header"><%= @recipe.name %></h2>
<div class="details">
    <div class="form-check">
      <% if @recipe.public == false %>
        <%= check_box :public, checked: false  %>
        <label class="check-label" for="unchecked">Public</label>
      <% else %>
        <%= check_box :public, checked: true %>
        <label class="check-label" for="checked">Public</label>
      <%end%>
    </div>

  <div class="time">
    <p>Preparation time: </p>
    <span><%=@recipe.preparation_time %></span>
  </div>
  <div class="time">
    <p>Cooking time: </p>
    <span><%=@recipe.cooking_time %></span>
  </div>

  <div class='res'>
    <p><strong>Description: <br> <%= @recipe.description %> </strong><br></p>
  </div>
<hr>
 <div class="links">
        <div class='btn-shoplist'>
            <%= link_to "Generate shopping list", general_shopping_list_path %>
        </div>
        <div class='btn-addingred'>
            <%= link_to "Add ingredient", new_recipe_recipe_food_path(@recipe) %>
        </div>
    </div>

<table class='table'>
 <% if @recipe.recipe_foods.any? %>
    <thead>
        <tr>
        <th>Food</th>
        <th>Quantity</th>
        <th>Value</th>
        <th>Action</th>
        </tr>
    </thead>
    <tbody>
    <% @recipe.recipe_foods.each do |food|%>
    <tr>
      <td><%= food.food.name%></th>
      <td><%= food.quantity%></td>
      <td><%= food.quantity * food.food.price %></td>
      <% if can? :delete, @recipe %>
 <td>
        <%=link_to "Delete", recipe_recipe_food_path(@recipe, food), method: :delete%>
      </td>
    <% end %>
    <% if cannot? :delete, food %>
  <td>No actions available</td>
<% end %>
    </tr>
    <%end%>
    </tbody>
  <%end%>
</table>

  <div class="links">
  <%= link_to "Back to recipes", recipes_path %>
  </div>
</div>