config/routes.rb
Rails.application.routes.draw do
  devise_for :users, sign_out_via: [:get]
    resources :users
    resources :foods
    resources :recipes do
    resources :recipe_foods, only: %i[new create destroy]
  end
  root 'foods#index'
  get '/general_shopping_list', to: 'foods#general'
  get '/public_recipes', to: 'recipes#public'
end

app/models/food.rb
class Food < ApplicationRecord
  has_many :recipe_foods, foreign_key: 'food_id'
  has_many :recipes, through: :recipe_foods
  belongs_to :user

  validates :name, presence: true, length: { maximum: 250 }
  validates :measurement_unit, presence: true
  validates :price, presence: true, comparison: { greater_than_or_equal_to: 0 }
end

app/controllers/foods_controller.rb
class FoodsController < ApplicationController
  load_and_authorize_resource
  # GET /foods
  def index
    @foods = Food.all
  end

  # GET /foods/new
  def new
    @food = Food.new
  end

  # POST /foods or /foods.json
  def create
    food = current_user.foods.new(food_params)
    # @food.user = current_user

    if food.save
      flash[:notice] = 'Food is successfully created'
      redirect_to foods_path
    else
      flash[:notice] = 'Invalid Entry'
      redirect_to new_food_path
    end
  end

  def general
    @foods = current_user.foods
    current_user.recipes.map do |recipe|
      recipe.recipe_foods.map do |recipe_food|
        food = recipe_food.food
        test = @foods.select { |f| f.name == food.name }[0]
        test.quantity = test.quantity - recipe_food.quantity
      end
    end
    @foods = @foods.select { |f| f.quantity.negative? }
    @foods.each { |f| f.quantity *= -1 }
    @total = 0
    @foods.each do |food|
      @total += (food.price * food.quantity)
    end
  end

  # DELETE /foods/1 or /foods/1.json
  def destroy
    @food = Food.all.find(params[:id])
    @food.recipe_foods.destroy_all
    if @food.destroy
      flash[:notice] = 'Food was deleted successfully.'
    else
      flash.now[:alert] = 'There was an error deleting the food.'
    end
    redirect_to foods_path
  end

  private

  # Only allow a list of trusted parameters through.
  def food_params
    params.require(:food).permit(:name, :measurement_unit, :price, :quantity, :user_id)
  end
end

app/views/foods/_food.html.erb
<div id="<%= dom_id food %>">
</div>

app/views/foods/_form.html.erb
<%= form_with(model: food) do |form| %>
  <% if food.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(food.errors.count, "error") %> prohibited this food from being saved:</h2>

      <ul>
        <% food.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/foods/edit.html.erb
<h1>Editing food</h1>

<%= render "form", food: @food %>

<br>

<div>
  <%= link_to "Show this food", @food %> |
  <%= link_to "Back to foods", foods_path %>
</div>

app/views/foods/general.html.erb
<div class="general-list-container">
    <h3>Shopping List</h3>
    <div class='items-amount'>
      <div>
      <span>Amount of food items to buy: </span>
      <span>&nbsp;<%= @foods.length %></span>
      </div>

      <div class='rest'>
      <span>Total value of food needed:</span>
      <span>&nbsp;<%= @total %></span>
      </div>
    </div>

    <table class="table">
      <thead>
        <tr>
          <th>Food</th>
          <th>Quantity</th>
          <th>Value</th>
        </tr>
      </thead>
      <tbody>
        <% @foods.each do |food| %>
          <tr>
            <td><%= food.name %></td>
             <td><%= food.quantity %> grams</td>
            <td>$<%= food.price %></td>
          </tr>
        <% end %>
      </tbody>
    </table>
  </div>

app/views/foods/index.html.erb
<div class="add-food">
<%= link_to "Add Food", new_food_path, class: "Add_food" %>
</div>
<table>
  <tr>
    <th>Name</th>
    <th>Measurement Unit</th>
    <th>Unit Price</th>
    <th>Action</th>
  </tr>
  <% @foods.each_with_index do |food, index| %>
    <%= render food %>
  <tr>
    <td><%= food.name %></td>
    <td><%= food.measurement_unit %></td>
    <td><%= food.price %></td>
    <% if can? :delete, food %>
  <td><%= button_to "REMOVE", food_path(id: food.id), method: :delete %></td>
<% end %>
<% if cannot? :delete, food %>
  <td>No actions available</td>
<% end %>
  </tr>
    <% end %>
</table>

app/views/foods/new.html.erb
<div class="form-wrapper">
<h1>New food</h1>

<%= form_with model: @food do |form| %>
  <div>
    <%= form.label :name %><br>
    <%= form.text_field :name %>
  </div>
  <div>
    <%= form.label :measurement_unit %><br>
    <%= form.text_field :measurement_unit %>
  </div>
<div>
    <%= form.label :quantity %><br>
    <%= form.number_field :quantity %>
  </div>
  <div>
    <%= form.label :price %><br>
    <%= form.number_field :price %>
  </div>
  <div class="submit">
    <%= form.submit  %>
  </div>
<% end %>

<br>

<div>
  <%= link_to "Back to foods", foods_path %>
</div>
</div>

app/views/foods/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @food %>

<div>
  <%= link_to "Edit this food", edit_food_path(@food) %> |
  <%= link_to "Back to foods", foods_path %>

  <%= button_to "Destroy this food", @food, method: :delete %>
</div>