config/routes.rb
Rails.application.routes.draw do
  devise_for :users, sign_out_via: [:get]
    resources :users
    resources :foods
    resources :recipes do
    resources :recipe_foods, only: %i[new create destroy]
  end
  root 'foods#index'
  get '/general_shopping_list', to: 'foods#general'
  get '/public_recipes', to: 'recipes#public'
end

app/views/layouts/_navbar.html.erb
<nav class="navbar">
  <div class='nav-buttons'>
     <% if current_user%>
      <%= form_with url: foods_path, method: :get do %>
        <button class='list'>Foods</button>
      <% end %>
      <%= form_with url: recipes_path, method: :get do %>
        <button class='list'>Recipes</button>
      <% end %>
      <%= form_with url: public_recipes_path, method: :get do %>
        <button class='list'>Public Recipes</button>
      <% end %>
      <%= form_with url:general_shopping_list_path, method: :get do %>
        <button class='list'>General Shopping List</button>
      <% end %>
      <% end %>
  </div>
  <div class='nav-list'>
    <% unless current_user%>
    <%= form_with model: User.new, url: new_user_session_path, method: :get, class:'log' do %>
      <button> Sign in</button>
    <% end %>
    <%= form_with model: User.new, url: new_user_registration_path, method: :get, class:'log' do %>
      <button>Sign up</button>
    <% end %>
  <% end %>
  <% if current_user %>
      <%= link_to "Sign-out", destroy_user_session_path %>
    <span class='alert'>
     <p>Welcome <%= current_user.name%></p>
    </span>
  <% end %>
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RecipeApp</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.3.1/dist/css/bootstrap.min.css"
    integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
  </head>

  <body>
    <p class="notice"><%= notice %></p>
       <p class="alert"><%= alert %></p>
       <header>
       <%= render "layouts/navbar" %>
       </header>
    <%= yield %>

    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/popper.js@1.14.7/dist/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@4.3.1/dist/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>
  </body>
</html>